FROM apache/airflow:2.10.5-python3.12

USER root

RUN groupadd airflow && usermod -aG airflow airflow

COPY . /home/airflow/credit-default-pipeline 
RUN chown -R airflow:airflow /home/airflow/credit-default-pipeline 

USER airflow

WORKDIR /home/airflow/credit-default-pipeline 

RUN pip install .
RUN dvc init --no-scm
