preprocess_data:
  random_seed: 3214
  test_size: 0.3

train:
  colsample_bytree: 0.7583231848290068
  gamma: 0.0
  learning_rate: 0.0038639770201776957
  max_depth: 50
  n_estimators: 609
  scale_pos_weight: 100
  subsample: 0.4

val_split:
  random_state: 3214
  test_size: 0.15


engineer_features:
  n_features_to_select: 6
  n_estimators: 200
